services:
  - type: web
    name: ahmuko-backend
    env: node
    buildCommand: |
      cp backend-package.json package.json
      cp tsconfig.backend.json tsconfig.json
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        sync: false
